---
- name: 'Ensure sysvinit services are defined properly'
  ansible.builtin.assert:
    that:
      # _service.arguments
      - '(_service.arguments is defined) | ternary(_service.arguments | default(None) is string, true)'
      - '(_service.arguments is defined) | ternary(_service.arguments | default(None) != None, true)'
      - "(_service.arguments is defined) | ternary(_service.arguments | default(None) != '', true)"

      # _service.daemonize
      - >-
          (_service.daemonize is defined) | ternary(_service.daemonize | default(None) | bool | string
          == _service.daemonize | default(None) | string, true)
      - '(_service.daemonize is defined) | ternary(_service.daemonize | default(None) is boolean, true)'

      # _service.pattern
      - '(_service.pattern is defined) | ternary(_service.pattern | default(None) is string, true)'
      - '(_service.pattern is defined) | ternary(_service.pattern | default(None) != None, true)'
      - "(_service.pattern is defined) | ternary(_service.pattern | default(None) != '', true)"

      # _service.runlevels
      - >-
          (_service.runlevels is defined) | ternary(_service.runlevels | default([]) | list | string
          == _service.runlevels | default(None) | string, true)
      - '(_service.runlevels is defined) | ternary(_service.runlevels | default([]) is sequence, true)'

      # _service.sleep
      - >-
          (_service.sleep is defined) | ternary(_service.sleep | default(None) | int | string
          == _service.sleep | default(None) | string, true)
      - '(_service.sleep is defined) | ternary(_service.sleep | default(None) is number, true)'
      - '(_service.sleep is defined) | ternary(_service.sleep | default(None) is integer, true)'
      - '(_service.sleep is defined) | ternary(_service.sleep | default(None) >= 1, true)'

    success_msg: 'Services are defined correctly'
    fail_msg: 'One or more services failed to validated correctly'
    quiet: '{{ _svm_quiet_assert }}'
  loop: '{{ _svm_services }}'
  loop_control:
    loop_var: '_service'

- name: 'Ensure sysvinit services have the desired configuration and state'
  ansible.builtin.sysvinit:
    name: '{{ _service.name | default(omit) }}'
    state: '{{ _service.state | default(omit) }}'
    enabled: '{{ _service.enabled | default(omit) }}'
    pattern: '{{ _service.pattern | default(omit) }}'
    arguments: '{{ _service.arguments | default(omit) }}'
    daemonize: '{{ _service.daemonize | default(omit) }}'
    runlevels: '{{ _service.runlevels | default(omit) }}'
    sleep: '{{ _service.sleep | default(omit) }}'
  become: true
  loop: '{{ _svm_services }}'
  loop_control:
    loop_var: '_service'
...
